### ISSUE TITLE
Support new maven prefix for imports

### ISSUE THREAD

**Issue by DiegoCoronel** [renatoathaydes/ceylon-gradle-plugin#13]
Now we can import in modules.ceylon with the prefix: maven, 

``` ceylon
native("jvm")
module flight "1.0.0" {
    import ceylon.interop.java "1.2.3";

    import "org.springframework.boot:spring-boot-starter-web" "1.3.3.RELEASE";
    import "org.springframework.boot:spring-boot-starter-undertow" "1.3.3.RELEASE";
    import "org.springframework.cloud:spring-cloud-starter-eureka" "1.1.0.RC1"; 

    shared import "org.springframework.boot:spring-boot-starter-data-jpa" "1.3.3.RELEASE";

    import "maven:postgresql:postgresql" "9.1-901-1.jdbc4"; //Using new prefix here
    import "org.liquibase:liquibase-core" "3.4.2";
}

```

but when i tried it with the plugin i got this error:

```
* What went wrong:
Execution failed for task ':resolveCeylonDependencies'.
> Could not resolve all dependencies for configuration ':ceylonCompile'.
   > Could not find maven:postgresql:postgresql.
     Searched in the following locations:
         file:/Users/DiegoCoronel/.m2/repository/maven/postgresql/postgresql/postgresql-postgresql.pom
         file:/Users/DiegoCoronel/.m2/repository/maven/postgresql/postgresql/postgresql-postgresql-9.1-901-1.jdbc4.jar
         https://repo1.maven.org/maven2/maven/postgresql/postgresql/postgresql-postgresql.pom
         https://repo1.maven.org/maven2/maven/postgresql/postgresql/postgresql-postgresql-9.1-901-1.jdbc4.jar
         https://repo.spring.io/libs-milestone/maven/postgresql/postgresql/postgresql-postgresql.pom
         https://repo.spring.io/libs-milestone/maven/postgresql/postgresql/postgresql-postgresql-9.1-901-1.jdbc4.jar
     Required by:
         :flight:unspecified
```

It looks that `maven` is added as folder.

**Comment by renatoathaydes** [comment]
I will add that. Do you have a link to something that documents the (as far as I know, new)  `maven:` prefix and why it was added?

**Comment by DiegoCoronel** [comment]
Humm, I dont remember to see any documentation about this, but I know that @quintesse is the author of this change, can you help with @renatoathaydes question?

**Comment by quintesse** [comment]
Why? Because we needed it ;)

We added Maven support at a certain point but without thinking too much about the future. So recently we needed support for NPM imports and that made it possible to have conflicting imports (an NPM import could look like a regular Ceylon import).

So I decided to add "namespaces", a NPM import for example needs to be prefixed with `npm:` to be used. Ceylon imports belong to the `ceylon:` namespace (but you never need to use that one, it's the default) and Maven imports belong to the `maven:` namespace. This way it's easy to add more types of imports in the future and we won't get confused as to what module we're talking about and where it should come from.

For Maven it was decided to keep the current backward compatibility as much as possible, meaning that if it looks like a Maven import we'll still treat it as one, but unfortunately Maven artifacts that have a group id consisting of a single word are ambiguous with this new namespaces system so they now _require_ that you prefix them with `maven:`.

**Comment by renatoathaydes** [comment]
> Maven artifacts that have a group id consisting of a single word are ambiguous with this new namespaces system so they now require that you prefix them with maven:.

@quintesse 
I don't see why this is the case.

Given a import `import "junit:junit" "4.13";`, there's no ambiguity because `junit` cannot be a prefix (the only prefixes I see implemented are `ceylon`, `maven` and `npm`, right?), so this must be a Maven import (because it contains a `:`).

I am implementing the module parser for the Gradle plugin, so I need to know if I am missing something.

**Comment by quintesse** [comment]
> there's no ambiguity because junit cannot be a prefix 

Namespaces are completely free to be defined. You can plug in your own repository implementations that respond to whatever namespace you want. Maybe `junit` would never be a logical option but Maven has hundreds of single-word group names, I'm sure some of them could easily conflict with a namespace we'd like to use in some future.

Like I said somewhere else the rules are very very simple, the new format is:

```
import "[<namespace>:]<identifier>" "<version>"
```

Where `<namespace>` can only consist of letters (I might add digits too, I haven't decided yet).
This means that except for the plain Ceylon imports _all_ other repositories must have an associated namespace.
The **only** exception I allowed was for Maven names if, and only if, they are unambiguous according to the new system, meaning `junit:junit` is out because it can not be distinguished from an import form the `junit` namespace. So only Maven import of the type `xxx.yyy.zzz:foo` are automatically converted.

We're _not_ going to use hard-coded lists or registries because I want to be able to look at an import and know 100% for sure what it points to without having to look up anything.

So the only dynamic thing I added in Ceylon is that I treat imports differently if they come from a module compiled with Ceylon 1.2.2 or before or with a newer compiler.

**Comment by quintesse** [comment]
Ok, hopefully this will make people happy. After a change I made to the language parser the import namespace is now part of the syntax of the import statement itself, instead of being something that was part of the module identifier string. So imports with namespaces now look like this:

```
import [namespace:]module.identifier "version";
import [namespace:]"some-other-identifier" "version";
```

or less abstract, a Maven import would look like this:

```
import maven:"junit:junit" "4.12";
```

In general this is nicer because the parser can now actually validate the namespace format (a plain identifier).

But an added advantage is that old Maven imports aren't ambiguous anymore! So _all_ old imports will continue to work unchanged! (We do give a warning because the version with an explicit prefix is preferred)
