### ISSUE TITLE
Use config file settings where possible

### ISSUE THREAD

**Issue by quintesse** [renatoathaydes/ceylon-gradle-plugin#15]
It would be nice if the `compileCeylon` and `runCeylon` tasks would make use of the config file settings by default. For example:
- **compiler.module** - for the default module(s) to compile
- **runtool.module** - for the default module to run
- **runtool.run** - for the toplevel to run

which are new. But I'm not sure if the plugin even looks at the older settings like:
- **compiler.source** - the source directory(ies) to use
- **compiler.resource** - the resource directory(ies) to use

but perhaps they are already automatically picked up by the compiler as long as the plugin doesn't specifically override them (didn't test).

**Comment by renatoathaydes** [comment]
The plugin never looked at those settings...

Not hard to do, though.

**Comment by quintesse** [comment]
Btw, the best option would be to use the `DefaultToolOptions` class, which has a bunch of static methods for retrieving all those settings. It's the best option because it takes care of providing default values as well as backward-compatibility when options change etc. It gives us a central place to change things related to default settings.

**Comment by renatoathaydes** [comment]
All of these properties can be defined in the configuration of the plugin in the build file. I can make the plugin use the config file settings if none is specified, otherwise override it with the one specified in the build file.

It's duplicating things, but I think some people will prefer to do it the Gradle way, others the pure Ceylon way... so why not keep both!? Will do that..

**Comment by renatoathaydes** [comment]
@quintesse can you check the above commit to see if I am going in the right direction?

**Comment by renatoathaydes** [comment]
Released the fix on version 1.3.1.
